apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-app-deployment
  namespace: short-app
spec:
  replicas: 1
  # Тут происходит связь Deployment c pod (по lables, которые указаны в template pod)
  selector:
    matchLabels:
      components: frontend
  template:
    metadata:
      labels:
        components: frontend
    spec:
      # тут может быть список контейнеров
      containers:
        - name: short-app
          image: antonlarichev/short-app:v1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "500m"
              memory: "128Mi"
          # тут может быть список портов
          ports:
            - containerPort: 80
            


